name: CI
on:
  schedule:
    - cron: '0 2 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
      - uses: AnnikaCodes/install-ziglint@v0.1
      - run: npm ci
      - run: npm run integration
      - run: npm pack
      - run: mv pkmn-ai-latest.tgz 0-ERROR.tar.gz
      - run: gh release delete latest --cleanup-tag --yes
      - run: gh release create latest -p -t Latest -n https://pkmn.cc/0-ERROR.tar.gz 0-ERROR.tar.gz
